[package]
name = "varys"
version = "0.1.0"
edition = "2021"
authors = ["Milan van Zanten <milan@milan.wtf>"]
description = "Spying on smart speakers."
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.17"
tts = "0.25.3"
#config = "0.13.1"
