version: '3'

services:
    database:
        image: 'postgres:latest'
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: LdWP6tYK
        volumes:
            - ./data/db/:/var/lib/postgresql/data/
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
