[package]
name = "varys"
version = "0.1.0"
edition = "2021"
authors = ["Milan van Zanten <milan@milan.wtf>"]
description = "Spying on smart speakers."
license = "MIT"
publish = false

[dependencies]
speaker = { path = "../speaker" }
log = "0.4"
pretty_env_logger = "0.5"
thiserror = "1.0"
